# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=200)),
                ('carnum', models.CharField(max_length=200)),
                ('slat', models.CharField(max_length=200)),
                ('slong', models.CharField(max_length=200)),
                ('dlat', models.CharField(max_length=200)),
                ('dlong', models.CharField(max_length=200)),
                ('highlighted', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
